### ISSUE TITLE
404 at root URL

### ISSUE THREAD

**Issue by christopher-baek** [elibroadfoot/elibroadfoot.github.io#1]
When I visit https://elibroadfoot.github.io/, I get a 404. Is there an index.html page?

**Comment by elibroadfoot** [comment]
Yes there is, but it is in the Pages directory. is there a way to have it look in that directory at startup?

**Comment by christopher-baek** [comment]
When a user opens https://elibroadfoot.github.io/ in a browser, the server is going to try to serve https://elibroadfoot.github.io/index.html. If you want your "home page" to be https://elibroadfoot.github.io/Pages/index.html, you could have your https://elibroadfoot.github.io/index.html page redirect your user to https://elibroadfoot.github.io/Pages/index.html using JavaScript.

It's generally a good idea to have _something_ at the root because otherwise the user has to idea where to navigate.

Check out the Window.location API to see how to make this happen: https://developer.mozilla.org/en-US/docs/Web/API/Window/location

**Comment by elibroadfoot** [comment]
Moved index.html into root, problem should be fixed now.
